/usr/local/lib/python2.6/dist-packages/pyplusplus/function_transformers/function_transformation.py:8: DeprecationWarning: the md5 module is deprecated; use hashlib instead
  import md5
INFO Parsing source file "ta_gendoc.h" ... 
INFO gccxml cmd: /usr/bin/gccxml  -I"/usr/local/include/Emergent" -I"/usr/local/include/Emergent" -I"/usr/include/qt4" -I"/usr/include/qt4/Qt" -I"/usr/include/qt4/QtCore" -I"/usr/local/include/Emergent"   "ta_gendoc.h" -fxml="/tmp/tmpdgZ3tL.xml"
/usr/local/lib/python2.6/dist-packages/pygccxml/parser/source_reader.py:151: DeprecationWarning: os.popen4 is deprecated.  Use the subprocess module.
  input_, output = os.popen4( command_line )
INFO GCCXML version - 0.9 BUGGY( 1.121 )
/usr/local/lib/python2.6/dist-packages/pygccxml/parser/scanner.py:343: UserWarning: unable to find out array size from expression ""
  warnings.warn( msg )

WARNING: static String_PArray * taGenDoc::TypeDef_Get_Parents(TypeDef * td, String_PArray * bp) [member function]
> compilation error W1050: The function returns "String_PArray *" type.
> You have to specify a call policies.Be sure to take a look on `Py++`
> defined call policies

WARNING: MemberDef [class]
> execution error W1040: The declaration is unexposed, but there are
> other declarations, which refer to it. This could cause "no to_python
> converter found" run time error. Declarations:   static bool
> taGenDoc::MemberSpace_Filter_Member(MemberSpace * ths, MemberDef * md)
> [member function]

WARNING: MemberSpace [class]
> execution error W1040: The declaration is unexposed, but there are
> other declarations, which refer to it. This could cause "no to_python
> converter found" run time error. Declarations:   static bool
> taGenDoc::MemberSpace_Filter_Member(MemberSpace * ths, MemberDef * md)
> [member function]

WARNING: MethodSpace [class]
> execution error W1040: The declaration is unexposed, but there are
> other declarations, which refer to it. This could cause "no to_python
> converter found" run time error. Declarations:   static bool
> taGenDoc::MethodSpace_Filter_Method(MethodSpace * ths, MethodDef * md)
> [member function]

WARNING: MethodDef [class]
> execution error W1040: The declaration is unexposed, but there are
> other declarations, which refer to it. This could cause "no to_python
> converter found" run time error. Declarations:   static bool
> taGenDoc::MethodSpace_Filter_Method(MethodSpace * ths, MethodDef * md)
> [member function]

WARNING: TypeDef [class]
> execution error W1040: The declaration is unexposed, but there are
> other declarations, which refer to it. This could cause "no to_python
> converter found" run time error. Declarations:   static bool
> taGenDoc::TypeDef_Filter_Type(TypeDef * td, TypeSpace * ts) [member
> function]  static String_PArray *
> taGenDoc::TypeDef_Get_Parents(TypeDef * td, String_PArray * bp)
> [member function]

WARNING: TypeSpace [class]
> execution error W1040: The declaration is unexposed, but there are
> other declarations, which refer to it. This could cause "no to_python
> converter found" run time error. Declarations:   static void
> taGenDoc::GenDoc(TypeSpace * ths, std::fstream & strm) [member
> function]  static bool taGenDoc::TypeDef_Filter_Type(TypeDef * td,
> TypeSpace * ts) [member function]

WARNING: String_PArray [class]
> execution error W1040: The declaration is unexposed, but there are
> other declarations, which refer to it. This could cause "no to_python
> converter found" run time error. Declarations:   static String_PArray
> * taGenDoc::TypeDef_Get_Parents(TypeDef * td, String_PArray * bp)
> [member function]  static String_PArray *
> taGenDoc::TypeDef_Get_Parents(TypeDef * td, String_PArray * bp)
> [member function]

INFO: file "PyEmergent.cpp" - updated( 0.000000 seconds )
Trying:
    from PyEmergent import *
Expecting nothing
ok
Trying:
    hi = hello('California')
Expecting nothing
**********************************************************************
File "/mnt/dream/home/dream/mingus/emergent/plugins/PyEmergent/BoostPython/test_PyEmergent.py", line 7, in test_PyEmergent
Failed example:
    hi = hello('California')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1241, in __run
        compileflags, 1) in test.globs
      File "<doctest test_PyEmergent[1]>", line 1, in <module>
        hi = hello('California')
    NameError: name 'hello' is not defined
Trying:
    hi.greet()
Expecting:
    'Hello from California'
**********************************************************************
File "/mnt/dream/home/dream/mingus/emergent/plugins/PyEmergent/BoostPython/test_PyEmergent.py", line 8, in test_PyEmergent
Failed example:
    hi.greet()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1241, in __run
        compileflags, 1) in test.globs
      File "<doctest test_PyEmergent[2]>", line 1, in <module>
        hi.greet()
    NameError: name 'hi' is not defined
Trying:
    invite(hi)
Expecting:
    'Hello from California! Please come soon!'
**********************************************************************
File "/mnt/dream/home/dream/mingus/emergent/plugins/PyEmergent/BoostPython/test_PyEmergent.py", line 10, in test_PyEmergent
Failed example:
    invite(hi)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1241, in __run
        compileflags, 1) in test.globs
      File "<doctest test_PyEmergent[3]>", line 1, in <module>
        invite(hi)
    NameError: name 'invite' is not defined
Trying:
    hi.invite()
Expecting:
    'Hello from California! Please come soon!'
**********************************************************************
File "/mnt/dream/home/dream/mingus/emergent/plugins/PyEmergent/BoostPython/test_PyEmergent.py", line 12, in test_PyEmergent
Failed example:
    hi.invite()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1241, in __run
        compileflags, 1) in test.globs
      File "<doctest test_PyEmergent[4]>", line 1, in <module>
        hi.invite()
    NameError: name 'hi' is not defined
Trying:
    class wordy(hello):
        def greet(self):
            return hello.greet(self) + ', where the weather is fine'
Expecting nothing
**********************************************************************
File "/mnt/dream/home/dream/mingus/emergent/plugins/PyEmergent/BoostPython/test_PyEmergent.py", line 15, in test_PyEmergent
Failed example:
    class wordy(hello):
        def greet(self):
            return hello.greet(self) + ', where the weather is fine'
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1241, in __run
        compileflags, 1) in test.globs
      File "<doctest test_PyEmergent[5]>", line 1, in <module>
        class wordy(hello):
    NameError: name 'hello' is not defined
Trying:
    hi2 = wordy('Florida')
Expecting nothing
**********************************************************************
File "/mnt/dream/home/dream/mingus/emergent/plugins/PyEmergent/BoostPython/test_PyEmergent.py", line 19, in test_PyEmergent
Failed example:
    hi2 = wordy('Florida')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1241, in __run
        compileflags, 1) in test.globs
      File "<doctest test_PyEmergent[6]>", line 1, in <module>
        hi2 = wordy('Florida')
    NameError: name 'wordy' is not defined
Trying:
    hi2.greet()
Expecting:
    'Hello from Florida, where the weather is fine'
**********************************************************************
File "/mnt/dream/home/dream/mingus/emergent/plugins/PyEmergent/BoostPython/test_PyEmergent.py", line 20, in test_PyEmergent
Failed example:
    hi2.greet()
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1241, in __run
        compileflags, 1) in test.globs
      File "<doctest test_PyEmergent[7]>", line 1, in <module>
        hi2.greet()
    NameError: name 'hi2' is not defined
Trying:
    invite(hi2)
Expecting:
    'Hello from Florida! Please come soon!'
**********************************************************************
File "/mnt/dream/home/dream/mingus/emergent/plugins/PyEmergent/BoostPython/test_PyEmergent.py", line 22, in test_PyEmergent
Failed example:
    invite(hi2)
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.6/doctest.py", line 1241, in __run
        compileflags, 1) in test.globs
      File "<doctest test_PyEmergent[8]>", line 1, in <module>
        invite(hi2)
    NameError: name 'invite' is not defined
1 items had no tests:
    test_PyEmergent.run
**********************************************************************
1 items had failures:
   8 of   9 in test_PyEmergent
9 tests in 2 items.
1 passed and 8 failed.
***Test Failed*** 8 failures.

EXIT STATUS: 8
